version: "3.0"
services:
  go:
    image: yue7090/go
    privileged: true
    container_name: yan-pm2go
    restart: always
    tty: true
    environment:
      - GOPATH=/var/www
      - GOROOT=/usr/local/go
      - PATH=$PATH:/usr/bin:/usr/local/bin:/usr/local/go/bin:/var/www/bin
      - GOPROXY=https://goproxy.io
    ports:
      - "1081:9000"
    volumes:
      - ./src:/var/www/src:rw